# Generated by Django 4.1 on 2022-09-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=2000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('msg_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever_user', to=settings.AUTH_USER_MODEL)),
                ('msg_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
