# Generated by Django 4.1 on 2022-09-06 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessages',
            name='msg_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_receiver_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directmessages',
            name='msg_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msg_sender_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('req_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_receiver_user', to=settings.AUTH_USER_MODEL)),
                ('req_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_sender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
