# Generated by Django 4.1 on 2022-09-14 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platy', '0002_alter_directmessages_msg_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessages',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 15, 28, 6, 401119, tzinfo=datetime.timezone.utc)),
        ),
    ]
